---
title: "Google Books NGram"
subtitle: "Bit by Bit Series"
output: html_notebook
---

loading data

```{r}
library(tidyverse)

# traditional CSV "tab separated" (it's big)
raw1gram <- readRDS("../../data/ngrams_v1_years.rds")

head(raw1gram)
```

reading total counts

```{r}

totalCounts <- read_delim("./googlebooks-eng-all-totalcounts-20090715.txt", 
                          delim="\t", skip=1, col_types = "innn",
                          col_names=c("year","total.words","total.pages","total.books"))

head(totalCounts)
```

keeping only years as ngrams

```{r}

years <- raw1gram %>% 
  filter( ngram %in% 1850:2010 ) %>% 
  inner_join(totalCounts, by="year") %>% 
  select(ngram, year, word.count, total.words) %>% 
  mutate(word.freq = word.count/total.words)

head(years)

```

fig 3A

```{r}

years %>% 
  # taking some years
  filter(year>=1850, year <=2000) %>% 
  # the selected years "1grams"
  filter(ngram %in% c(1883,1910,1950)) %>% 
  # plot it
  ggplot(aes(x=year, y=word.freq, color=ngram)) +
    geom_line(size=1) +
    theme_light()

```

Vamos tentar refazer o decaimento exponencial dos livros achando a meia vida, mas desta vez vamos fazer estatisticamente melhor.

1o fazer o "slice" a partir do pico para cada ano

```{r}

# para cada ngram, acha o pico
peaks <- years %>% 
  # remove "referencias passadas"
  filter( year >= as.integer(ngram) ) %>% 
  group_by(ngram) %>% 
  filter( word.freq == max(word.freq) ) %>% 
  select(ngram, max.year=year, max.freq=word.freq) %>% 
  ungroup()

head(peaks)

decay.data <- years %>% 
  inner_join(peaks, by="ngram") %>% 
  # remove years before peak %>% 
  filter( year >= max.year )

head(decay.data)

decay.data %>% 
  filter( ngram %in% as.character(sample(1850:1980, 10))) %>% 
  ggplot(aes(x=year, y=word.freq, color=ngram)) +
  geom_line()+
  theme_minimal()

```

lets fit a exponential for each year

```{r}

# word.freq = alpha.exp(beta*year) + theta
calcHalfLife <- function(dt){
  model <- nls(word.freq ~ SSasymp(year, yf, y0, log_alpha), data=dt)
  k <- exp(coef(model)[3])
  hl.val <- -log(1/2)/k
  names(hl.val) <- "half.life"
  return( hl.val )
}

sf_calcHalfLIfe <- safely(calcHalfLife, NA, quiet = T)

hl <- decay.data %>% 
  group_by(ngram) %>% 
  nest() %>% 
  arrange(ngram) %>% 
  mutate( hl_calc = map(data, sf_calcHalfLIfe)) %>% 
  mutate( half_life = map_dbl(hl_calc, pluck, 1)) %>% 
  filter( !is.na(half_life) ) %>% 
  ungroup()


hl %>% 
  mutate(ngram=as.integer(ngram)) %>% 
  filter(ngram >= 1850, ngram <= 1975 ) %>% 
  ggplot(aes(x=ngram, y=half_life)) + 
  geom_point() +
  ylim(0,100) +
  theme_minimal()



```


